### PR TITLE
Adds futuristic cityscene with moon

### PR DESCRIPTION
**Pull request by aleksanb**
futuristic city

:D Development has begun :D

### CODE REVIEW

**Comment by cristeahub** [comment]
Awesome! \o/ Could you change the `WIP` commit?

**Comment by aleksanb** [comment]
Let's use the new squash from github merge feature :D

**Comment by iver56** [comment]
If we're going to include this in the demo, we need to decide where it should be soon

**Comment by aleksanb** [comment]
Parts have been salvaged. Closing.

**Pull request closed without merging**
