### PR TITLE
Use notes instead of cubes for particles in phonograph layer

### PR DESCRIPTION
**Pull request by iver56**
@stianjensen is this like what you had in mind?

### CODE REVIEW

**Comment by stianjensen** [comment]
Substantially more performance intensive at least!

**Comment by cristeahub** [comment]
Wow! Yes, I went down to around 2 fps on this scene. Hope this isn't an issue on the demo computer.

**Comment by iver56** [comment]
Opacity seems broken too. Maybe we should go back to just cubes?. With the current amount of bloom, you can't really see the notes anyway ^^ Depends on the camera position and angle.
Performance seems fine on my Thinkpad, albeit the fps drop is indeed noticeable

**Comment by cristeahub** [comment]
Maybe go back to cubes yes. It could be that the notes models have too many nodes in them, which in turn causes the lag, but I haven't checked this out.

**Pull request merged**
