### PR TITLE
Use NIN GA generation, depends on NIN backend support

### PR DESCRIPTION
**Pull request by aleksanb**
Depends on https://github.com/ninjadev/nin/pull/252

### CODE REVIEW

**Comment by stianjensen** [comment]
Why exactly is it better to store the id in nin.json than just keeping it with the analytics code?

**Comment by aleksanb** [comment]
Because you dont have to touch the GA code anymore, and it is built for you.
You could also create te other metadata manually but its Nice when its automatic. Also more explicit as you don't have to look I'm the index.html but in nin.json instead.

**Comment by stianjensen** [comment]
> Also more explicit as you don't have to look I'm the index.html but in nin.json instead.

Is the nin.json generated with the Google analytics property there so it's obvious to fill it in, too? In that case, I guess it serves as a nice reminder to add Google analytics tracking

**Comment by aleksanb** [comment]
Jup! Everything is put in by default, and index.html is always explicitly embedded in your project (no more default fallback, it's copied over).

**Comment by sigvef** [comment]
https://github.com/ninjadev/nin/pull/252 has been merged!

**Pull request merged**
