### PR TITLE
Add particles to end of twisterlayer

### PR DESCRIPTION
**Pull request by peterhgombos**

### CODE REVIEW

**Comment by iver56** [comment]
I think you meant **particles**, not articles :stuck_out_tongue_winking_eye:

**Comment by stianjensen** [comment]
> I think you meant particles, not articles 😜

I was so confused

**Comment by peterhgombos** [comment]
#it'sahackathon

**Comment by aleksanb** [comment]
Quick, embed our mastes thesopodes!

**Comment by lionleaf** [comment]
When jumping around you don't get to see the particles unless you hit the right magic frame number that spawns them

**Comment by peterhgombos** [comment]
Fixed!

**Pull request merged**
